# Generated by Django 5.0.6 on 2024-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0003_alter_reservation_user_delete_restaurant_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dauer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
