# Generated by Django 5.0.6 on 2024-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0004_reservation_dauer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='anmerkungen',
            field=models.TextField(blank=True),
        ),
    ]
