# Generated by Django 5.0.6 on 2024-06-14 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0006_reservation_gerichte_reservation_rabattcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='buchungsdatum',
            field=models.DateField(default=datetime.date(2024, 6, 14)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='buchungsuhrzeit',
            field=models.TimeField(default=datetime.time(12, 28, 39, 761994)),
        ),
    ]
