# Generated by Django 5.0.6 on 2024-06-14 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0007_reservation_buchungsdatum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='buchungsuhrzeit',
            field=models.TimeField(default=datetime.time(10, 30, 9, 588339)),
        ),
    ]
