# Generated by Django 5.0.6 on 2024-06-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0008_alter_reservation_buchungsuhrzeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='buchungsdatum',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='buchungsuhrzeit',
            field=models.TimeField(default=datetime.time(9, 48, 54, 346934)),
        ),
    ]
