# Generated by Django 5.0.6 on 2024-06-16 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0009_alter_reservation_buchungsdatum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='buchungsuhrzeit',
            field=models.TimeField(default=datetime.time(12, 41, 46, 697323)),
        ),
    ]
