# Generated by Django 5.0.6 on 2024-06-16 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0013_alter_reservation_buchungsuhrzeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='buchungsuhrzeit',
            field=models.TimeField(default=datetime.time(18, 18, 16, 260983)),
        ),
    ]
