# Generated by Django 5.0.6 on 2024-06-17 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0015_alter_reservation_buchungsdatum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='buchungsuhrzeit',
            field=models.TimeField(default=datetime.time(15, 56, 14, 860511)),
        ),
    ]
